export const CHOSE_MERGE_SORT = "CHOSE_MERGE_SORT";
export const CHOSE_SELECTION_SORT = "CHOSE_SELECTION_SORT";
export const CHOSE_BUBBLE_SORT = "CHOSE_BUBBLE_SORT";
export const CHOSE_INSERT_SORT = "CHOSE_INSERT_SORT";
